METEOGR_TIME_PERIOD_HOURS = 3

METEOGR_DAYTIME_FORMAT_CSV = "%d/%m/%Y--%H:%M:%S"

METEOGR_DAYTIME_FORMAT_FNAME = "%Y%m%d%H%M%S"

WIND_DIRECTION = ['N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NW', 'NNW']
