### ENUMERATED VARIABLES

WIND_DIRECTION = ['N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NW', 'NNW']

### ROUNDED DIGITS The number of decimals to use when rounding the number

ROUND_DIGITS_TEMP_F = 0

ROUND_DIGITS_KMH = 0

ROUND_DIGITS_MM = 4

### STRING FORMAT

DAYTIME_FORMAT_CSV = "%d/%m/%Y--%H:%M:%S"

DAYTIME_FORMAT_FNAME = "%Y%m%d%H%M%S"

DAYTIME_FORMAT_FIG = "%d/%m/%Y--%H:%M"

### FONTS & STYLE

FONT_BLACK_BACK_RED = '[5;30;41m'

FONT_WHITE_BACK_RED = '[0;37;41m'

FONT_BLACK_BACK_GREEN = '[6;30;42m'

FONT_WHITE_BACK_GREEN = '[0;37;42m'

PRINT_ERROR_COLOR = FONT_BLACK_BACK_RED

PRINT_SUCCS_COLOR = FONT_BLACK_BACK_GREEN

### FIGURE VARIABLES

FIG_DPI = 500

FIG_SIZE = (18.5, 10.5)

### PARAMETERS FOR METEO.GR

METEOGR_TIME_PERIOD_HOURS = 3

METEOGR_DAYTIME_FORMAT_FIG = DAYTIME_FORMAT_FIG

METEOGR_DAYTIME_FORMAT_CSV = DAYTIME_FORMAT_CSV

METEOGR_DAYTIME_FORMAT_FNAME = DAYTIME_FORMAT_FNAME


### PARAMETERS FOR WEATHER.COM

WEATHERCOM_TIME_PERIOD_HOURS = 1

WEATHERCOM_UNITS_USA = 1

WEATHERCOM_DAYTIME_FORMAT_FIG = DAYTIME_FORMAT_FIG

WEATHERCOM_DAYTIME_FORMAT_CSV = DAYTIME_FORMAT_CSV

WEATHERCOM_DAYTIME_FORMAT_FNAME = DAYTIME_FORMAT_FNAME


### PARAMETERS FOR WEATHERAVENUE.COM

WEATHERAVENUE_SKIP_FIRST_HOURS = 5

WEATHERAVENUE_SKIP_FIRST_TEMPS = 10

WEATHERAVENUE_SKIP_TEMPS = 2
