WIND_DIRECTION = ['N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NW', 'NNW']

###

FONT_BLACK_BACK_RED = '[5;30;41m'

FONT_WHITE_BACK_RED = '[0;37;41m'

FONT_BLACK_BACK_GREEN = '[6;30;42m'

FONT_WHITE_BACK_GREEN = '[0;37;42m'

PRINT_ERROR_COLOR = FONT_BLACK_BACK_RED

PRINT_SUCCS_COLOR = FONT_BLACK_BACK_GREEN


###

METEOGR_TIME_PERIOD_HOURS = 3

METEOGR_DAYTIME_FORMAT_CSV = "%d/%m/%Y--%H:%M:%S"

METEOGR_DAYTIME_FORMAT_FNAME = "%Y%m%d%H%M%S"


###

WEATHERCOM_TIME_PERIOD_HOURS = 1

WEATHERCOM_UNITS_USA = 1

WEATHERCOM_TEMP_UNIT_C = not(WEATHERCOM_UNITS_USA)

WEATHERCOM_DAYTIME_FORMAT_CSV = METEOGR_DAYTIME_FORMAT_CSV

WEATHERCOM_DAYTIME_FORMAT_FNAME = METEOGR_DAYTIME_FORMAT_FNAME

###

WEATHERAVENUE_SKIP_FIRST_HOURS = 5

WEATHERAVENUE_SKIP_FIRST_TEMPS = 10

WEATHERAVENUE_SKIP_TEMPS = 2
